### PR TITLE
fix: charset found was discarded due to default charset init

### PR DESCRIPTION
**Pull request by vallo87**

### CODE REVIEW

**Comment by smhg** [comment]
Thank you for this PR! Could you add at least one test for this issue? Then we're good to merge.

**Comment by vallo87** [comment]
sure, I'll get to it ASAP

**Comment by AlexMost** [comment]
Waiting for this PR to be merged and released - https://github.com/ttag-org/ttag-cli/issues/56

**Comment by smhg** [comment]
I've added a test that covers the case mentioned in #12.
This PR does not seem to address those issues, but it might actually fix a different issue?
I'll try to come up with a solution for #12 ASAP and then I'll be able to evaluate what needs to be done with this PR.

If however an independent issue, definitely feel free to submit a separate test case for which this solution applies.

**Comment by smhg** [comment]
Closing this PR as recent changes should have fixed this properly. More in issue #12.

**Pull request closed without merging**
