### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by kevinlul**
Re: https://github.com/smhg/gettext-parser/pull/72#issuecomment-1210030988

### CODE REVIEW

**Comment by kevinlul** [comment]
So I just double-checked, and this configuration only affects the line-endings upon staging, which is good but not actually the problem I was running into. I'm not sure if it's something that can be done automatically at the repository-level until after cloning, since the actual relevant factor is `git config core.autocrlf true`

**Comment by smhg** [comment]
@kevinlul it sounds best not to merge this, no?
It doesn't solve an issue if I understand correctly? And I don't have the knowledge to support this further down the road. Or you think it will be useful to others?

**Comment by kevinlul** [comment]
It solves a different issue — it helps ensure that files committed by Windows users have line endings normalized to LF, so the tests work as expected on Linux. It doesn't solve the problem that I was running into. Here's the relevant section of the gitattributes manpage for reference: https://git-scm.com/docs/gitattributes#_end_of_line_conversion

**Comment by smhg** [comment]
Merged, thank you!

**Pull request merged**
