### PR TITLE
#37 support unescaped double quotes

### LINKED ISSUE #37: Support unescaped double quotes in message strings & IDs
The gettext standard isn't clear on whether double quotes (`"`) should be escaped or not (see: https://stackoverflow.com/questions/10218631/printing-with-gettext).
However, not all translation management systems escape double quotes, so it would be good if `gettext-parser` could support unescaped `"`s. 
I'll add a PR with a failing test asap and a complete fix eventually.

### PR DESCRIPTION
**Pull request by TimKam**
**Support unescaped double quotes**
Closes #37
Adjusts the parser so that it only considers a double quote as closing if it's
at the end of the line/end of file.

### CODE REVIEW

**Comment by TimKam** [comment]
@smhg Could you take a look? :-)

**Comment by smhg** [comment]
I didn't get any email from GitHub about this repo last month. I'll have a look at you issue/PR tomorrow. Thanks!

**Comment by smhg** [comment]
Am I missing something or are there no unescaped quotes in `test/fixtures/unescaped_double_quotes.po`?

**Comment by TimKam** [comment]
Sorry! I guess I made a copy-and-paste mistake when updating the test file, will change that real quick.

**Comment by smhg** [comment]
As mentioned in #37: closing for now, but please reopen if appropriate.

**Pull request closed without merging**
