### PR TITLE
pocompiler: add trailing newline

### PR DESCRIPTION
**Pull request by kevinlul**
This makes the file POSIX-compliant, which is also the original ecosystem that gettext comes from.

### CODE REVIEW

**Comment by smhg** [comment]
@kevinlul Thank you for your contribution! I wasn't aware these were missing.
You definitely need to run the tests (and linting) when we move on with this (`npm run lint` and `npm test`). Can you have a look at that?

**Comment by kevinlul** [comment]
Side note: the tests on Windows seem to assume .gitattributes `* text=auto`, or at least for `*.po` and `*.pot`. They don't work if Git checks out the files with the original LF endings instead of converting them to CR LF!

**Comment by smhg** [comment]
> Side note: the tests on Windows seem to assume .gitattributes `* text=auto`, or at least for `*.po` and `*.pot`. They don't work if Git checks out the files with the original LF endings instead of converting them to CR LF!

I'm not experienced enough with Git: is this something that we can fix? Can you add it to this PR?

**Comment by kevinlul** [comment]
Yes, I'll make a separate PR as it's not specifically related to this issue. This one should be done unless you spot any other problems?

**Comment by smhg** [comment]
Thank you! Released as `6.0.0`.
Feel free to send that additional PR.

**Pull request merged**
