### PR TITLE
fix(compat): replace lookbehind regex with some logic to compatibility with Safari like browsers

### PR DESCRIPTION
**Pull request by Delagen**

### CODE REVIEW

**Comment by Delagen** [comment]
Seems to resolve #69

**Comment by Delagen** [comment]
@smhg Please review

**Comment by smhg** [comment]
`Array.at` seems to be a bit too new. Node 14 would still be nice to support I guess.
Can you change this to some alternative please?

**Comment by Delagen** [comment]
@smhg Thanks for reply, updated

**Pull request merged**
