### PR TITLE
Add `readable-stream` to the dependencies to fix an error with `stream` module

### PR DESCRIPTION
**Pull request by coolstuffit**

### CODE REVIEW

**Comment by coolstuffit** [comment]
Something wrong with the node version. It uses 0.10

**Comment by smhg** [comment]
Thank you for your contribution!
I'm ok with using readable-stream. But you'd need to make the tests work.
I scanned their readme: it seems version 2 is what you need to use. Can you give this a try?

**Comment by smhg** [comment]
@RignonNoel I'm fine with dropping support in a new major version.
In the meanwhile though, the 'fix' for this PR seems easy? Please correct me if I'm wrong.
If so, it sounds best to do small release and do a major version with some other features (and/or ES6 rewrite).

**Comment by RignonNoel** [comment]
@smhg Yes the fix it's pretty easy, my concern is more about the support of the version 2 since `readable-stream` write no one documentation about it. The version 3 is 7 months old and i really don't know if the team will support security issue in version 2.

You're right, you can just accept the PR #46 i created yesterday and wait before push a V3 if one day a security issue is discovered (or you added some new features)

**Comment by smhg** [comment]
Closing because this was fixed in #46.

**Comment by smhg** [comment]
@RignonNoel I've also released version 3, which removes old node support. That should fix any current security issues (in dev mode).

**Comment by RignonNoel** [comment]
@smhg thanks for your help on this! And thanks for this great lib and all the work invest in it :)

**Pull request closed without merging**
